/* global React */
/* SPLIT podcast — real episodes from dimolaw.com/podcast.
   Images live at assets/podcast/ relative to the host HTML. */

const PODCAST_EPISODES = [
  {
    n: 11,
    date: 'Apr 14, 2026',
    title: 'When Suspicion Meets Strategy: Divorce Law & Investigation',
    guest: 'With Jessica Zannetti',
    minutes: '20 min',
    listen: 'https://www.podomatic.com/podcasts/split88595/episodes/2026-04-14T06_00_00-07_00',
    img: 'assets/podcast/ep-11-divorce-law.webp',
    imgAlt: 'Divorce sign — Split podcast episode 11 with Jessica Zannetti',
  },
  {
    n: 10,
    date: 'Mar 10, 2026',
    title: 'The Biggest Trends Reshaping Divorce Law in 2026',
    guest: 'With Jill Spielberg, Esq., Abrams Fensterman',
    minutes: '23 min',
    listen: 'https://www.podomatic.com/podcasts/split88595/episodes/2026-03-10T06_33_25-07_00',
    img: 'assets/podcast/ep-10-divorce-trends-2026.webp',
    imgAlt: 'Divorce trends 2026 word cloud — Split podcast episode 10 with Jill Spielberg',
  },
  {
    n: 9,
    date: 'Feb 18, 2026',
    title: 'Divorce & Money: Financial Abuse, Hidden Assets, and Crypto',
    guest: 'With Nick Himonidis & Gus Dimopoulos',
    minutes: '34 min',
    listen: 'https://www.podomatic.com/podcasts/split88595/episodes/2026-02-17T06_00_00-08_00',
    img: 'assets/podcast/ep-09-divorce-and-money.webp',
    imgAlt: 'Couple pulling on banknote over legal documents — Split podcast episode 9',
  },
  {
    n: 8,
    date: 'Jan 27, 2026',
    title: 'Navigating Complex Dynamics in Divorce',
    guest: 'With Heidi Davidson & Gus Dimopoulos',
    minutes: '29 min',
    listen: 'https://www.podomatic.com/podcasts/split88595/episodes/2026-01-27T09_00_00-08_00',
    img: 'assets/podcast/ep-08-navigating-complex-dynamics-in-divorce.webp',
    imgAlt: 'Wedding rings on divorce papers being signed — Split podcast episode 8',
  },
  {
    n: 7,
    date: 'Jan 7, 2026',
    title: 'Safe Exchange and Supervised Visitation',
    guest: 'With Tiffany Hamilton, YWCA CEO',
    minutes: '31 min',
    listen: 'https://www.podomatic.com/podcasts/split88595/episodes/2026-01-06T06_00_00-08_00',
    img: 'assets/podcast/ep-07-safe-exchange-supervised-visitation.webp',
    imgAlt: 'Divorced parents during supervised visitation — Split podcast episode 7 with Tiffany Hamilton',
  },
  {
    n: 6,
    date: 'Dec 9, 2025',
    title: 'Litigation Strategy & Tactical Decision-Making',
    guest: 'With Heidi Davidson & Gus Dimopoulos',
    minutes: '36 min',
    img: 'assets/podcast/ep-06-litigation-strategy.webp',
    imgAlt: 'Lawyer forming divorce litigation strategy — Split podcast episode 6',
  },
  {
    n: 5,
    date: 'Nov 18, 2025',
    title: 'Parental Alienation: When Divorce Hurts More Than Just the Parents',
    guest: 'With Dr. Amy Baker',
    minutes: '28 min',
    img: 'assets/podcast/ep-05-parental-alienation.webp',
    imgAlt: 'Parents arguing behind alienated child — Split podcast episode 5 with Dr. Amy Baker',
  },
  {
    n: 4,
    date: 'Oct 28, 2025',
    title: 'Modern Divorce: Mediation, Gender Shifts & Snap Judgments',
    guest: 'With Matthew Cooper',
    minutes: '32 min',
    img: 'assets/podcast/ep-04-modern-divorce.webp',
    imgAlt: 'Modern divorce — Split podcast episode 4 with Matthew Cooper',
  },
  {
    n: 3,
    date: 'Oct 7, 2025',
    title: 'Narcissists, Love Bombs, & Red Flags: What You Missed (But Won\u2019t Again)',
    guest: 'With Dr. Kathleen McKay',
    minutes: '30 min',
    img: 'assets/podcast/ep-03-narcissism.webp',
    imgAlt: 'Narcissists, love bombs and red flags — Split podcast episode 3 with Dr. Kathleen McKay',
  },
  {
    n: 2,
    date: 'Sep 16, 2025',
    title: 'Divorce is Changing \u2014 And You Need to Know How',
    guest: 'With Lisa Zeiderman',
    minutes: '27 min',
    img: 'assets/podcast/ep-02-changes-in-modern-divorce.webp',
    imgAlt: 'Divorce is changing — Split podcast episode 2 with Lisa Zeiderman',
  },
  {
    n: 1,
    date: 'Sep 16, 2025',
    title: 'Permissive vs. Authoritative Parenting: Striking the Right Balance',
    guest: 'With Dr. Beth Raines',
    minutes: '26 min',
    img: 'assets/podcast/ep-01-permissive-parenting.webp',
    imgAlt: 'Permissive vs. authoritative parenting — Split podcast episode 1 with Dr. Beth Raines',
  },
];

window.PODCAST_EPISODES = PODCAST_EPISODES;
